config/routes.rb
Rails.application.routes.draw do
  resources :definitions

  resources :examples

  root 'definitions#index'

  get 'search', to: 'definitions#search'

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

end

app/models/definition.rb
class Definition < ActiveRecord::Base
  validates :word, presence: true, uniqueness: true
  validates :meaning, presence: true

  has_many :examples

  paginates_per 10

  def fancy?
    word.length > 16
  end

  def self.search(input)
    where("word LIKE ? OR meaning LIKE ?", "%#{input}%", "%#{input}%")
  end
end

app/models/example.rb
class Example < ActiveRecord::Base
  belongs_to :definition
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:github]

  def self.from_omniauth(auth)
    user = where(provider: auth['provider'], uid: auth['uid']).first_or_create

    user.name         = auth.info.name
    user.email        = auth.info.email
    user.nickname     = auth.info.nickname
    user.access_token = auth.credentials.token
    user.password     = Devise.friendly_token[0,20]
    user.save!

    return user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/definitions_controller.rb
class DefinitionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :search]
  before_action :set_definition, only: [:show, :edit, :update, :destroy]


  def index
    @definitions = Definition.all
    @definitions = Definition.order(:word).page params[:page]
  end

  def show
  end

  def search
    @definitions = Definition.search(params[:definition])
    @definitions = @definitions.order(:word).page params[:page]
  end

  def new
    @definition = Definition.new
  end

  def edit
  end

  def create
    @definition = Definition.new(definition_params)

    respond_to do |format|
      if @definition.save
        format.html { redirect_to @definition, notice: 'Definition was successfully created.' }
        format.json { render :show, status: :created, location: @definition }
      else
        format.html { render :new }
        format.json { render json: @definition.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @definition.update(definition_params)
        format.html { redirect_to @definition, notice: 'Definition was successfully updated.' }
        format.json { render :show, status: :ok, location: @definition }
      else
        format.html { render :edit }
        format.json { render json: @definition.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @definition.destroy
    respond_to do |format|
      format.html { redirect_to definitions_url, notice: 'Definition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private

  def set_definition
    @definition = Definition.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def definition_params
    params.require(:definition).permit(:word, :meaning, :word_type)
  end

end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  before_action :ensure_logged_in
  before_action :set_example, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
    @definition = Definition.find(params[:definition_id])
    @example = Example.new
  end

  def edit
  end

  def create
    @example = Example.new(example_params)

    respond_to do |format|
      if @example.save
        format.html { redirect_to definitions_path, notice: 'Example was successfully created.' }
        format.json { render :show, status: :created, location: @example }
      else
        format.html { render :new }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @example.update(example_params)
        format.html { redirect_to @example, notice: 'Example was successfully updated.' }
        format.json { render :show, status: :ok, location: @example }
      else
        format.html { render :edit }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @example.destroy
    respond_to do |format|
      format.html { redirect_to examples_url, notice: 'Example was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  def set_example
    @example = Example.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def example_params
    params.require(:example).permit(:usage)
  end

  def ensure_logged_in
    if current_user.nil?
      redirect_to new_session_path
      return false
    end
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Github") if is_navigational_format?
    else
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/definitions_helper.rb
module DefinitionsHelper
end

app/views/definitions/_form.html.erb
<%= form_for(@definition) do |f| %>
  <% if @definition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@definition.errors.count, "error") %> prohibited this definition from being saved:</h2>

      <ul>
      <% @definition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %>
    <%= f.text_field :word %>
    <%= f.label :type %>
    <%= f.select(:word_type, ['', 'noun', 'verb', 'pronoun', 'adverb', 'adjective', 'other']) %>
    <%= f.label :meaning %>
    <%= f.text_field :meaning, size: "50"%>
  </div>
  <div class="actions">
    <%= f.submit %><br>
    <div id="cancel"><%= link_to '', definitions_path, class: "glyphicon glyphicon-ban-circle"%></div>
  </div>
<% end %>

app/views/definitions/_search.html.erb
<td id="edit"><%= link_to '', edit_definition_path(definition), class: "glyphicon glyphicon-edit" %></td>
<td class="words"><%= link_to "#{definition.word}", definition %></td>
<td>:<%= definition.word_type %></td>
<td>:<%= definition.meaning %></td>
<td id="delete">
  <%= link_to '', definition, method: :delete, class: "glyphicon glyphicon-remove-sign", data: { confirm: 'Are you sure?' } %>
</td>

app/views/definitions/edit.html.erb
<h1>Editing Definition</h1>

<%= render 'form' %>

app/views/definitions/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Words</th>
      <th></th>
      <th>Meaning</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @definitions.each do |definition| %>
    <tr class="spaces">
      <% render 'search' %>
    </tr>
    <% end %>
  </tbody>
</table>
<div> <%= paginate @definitions %> </div>

app/views/definitions/new.html.erb
<h1>Thank you for contributing!</h1>

<%= render 'form' %>

app/views/definitions/search.js.erb
$(".spaces").html( $("<%= escape_javascript(render 'search') %>") )

app/views/definitions/show.html.erb
<p id="notice"><%= notice %></p>

<div id="show_word">
  <div><strong><%= @definition.word %></div>
    <span> -</strong><%= @definition.word_type %> </span>
  <p>
    <%= @definition.meaning %>
  </p>
  <div><%= link_to 'Add Example', new_example_path(definition_id: @definition.id) %></div>
  <div id="return"> <%= link_to '', definitions_path, class: "glyphicon glyphicon-arrow-left"%>
</div>

app/views/examples/_form.html.erb
<%= form_for(@example) do |f| %>
  <% if @example.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@example.errors.count, "error") %> prohibited this example from being saved:</h2>

      <ul>
      <% @example.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :example %>
    <%= f.text_field :usage %>
  </div>
  <div class="actions">
    <%= f.submit %><br>
    <div id="cancel"><%= link_to '', examples_path, class: "glyphicon glyphicon-ban-circle"%></div>
  </div>
<% end %>

app/views/examples/new.html.erb
<p id="notice"><%= notice %></p>

<div id="show_word">
  <div><strong><%= @definition.word %></div>
    <span> -</strong><%= @definition.word_type %> </span>
  <p>
    :<%= @definition.meaning %>
  </p>
  <%= render 'form' %>
  <div id="return"><%= link_to '', definitions_path, class: "glyphicon glyphicon-arrow-left"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dictionary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <script>
    window.fbAsyncInit = function() {
      FB.init({
        appId      : '1008917535818597',
        xfbml      : true,
        version    : 'v2.5'
      });
    };

    (function(d, s, id){
       var js, fjs = d.getElementsByTagName(s)[0];
       if (d.getElementById(id)) {return;}
       js = d.createElement(s); js.id = id;
       js.src = "//connect.facebook.net/en_US/sdk.js";
       fjs.parentNode.insertBefore(js, fjs);
     }(document, 'script', 'facebook-jssdk'));
  </script>
  <!-- <div class="fb-like" data-share="true" data-width="450" data-show-faces="true"></div> -->

  <div id="header">
    <nav class="navbar navbar-default">
      <a href="/"><img src="/brain_logo.jpg"/></a>
      <div id="homelink"><%= link_to '', definitions_path, class: "glyphicon glyphicon-home"%></div>
      <div id="nav_spacer">
        <% if user_signed_in? %>
        <div id="logout"><%= link_to "Logout", destroy_user_session_path, method: :delete, data: { confirm: "Is this really goodbye? :'(" } %></div>
        <% else %>
        <div id="login"><%= link_to "Login", new_user_session_path, method: :create %></div>
        <% end %>
      </div>
      <div id="add_word">
        <% if user_signed_in? %>
        <%= link_to 'ADD A WORD', new_definition_path %>
        <% else %>
        <div id="add_word"></div>
        <% end %>
      </div>
      <div id="search">
        <input id="to_search" type="text" placeholder=" Search for words" data-remote= "true">
      </div>
    </nav>
    <h1>---<@ Dictionary Database @>---</h1>
  </div>


  <%= yield %>

</body>
</html>